config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :notes
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'notes#index', as: :authenticated_root
    end
    
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'notes'

  before_action :set_note, only: [:show, :edit, :update]
  before_action :set_users_notes, only: [:index]
  before_action :validate_user_note, only: [:show, :edit]
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)  
    set_note_owner(@note)
    
    respond_to do |format|
      if @note.save
        format.html do
          redirect_to @note
          flash[:success] =  'Nota criada com sucesso!' 
        end
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html do 
          redirect_to @note
          flash[:success] = 'Atualizado com sucesso!'       
        end
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    DeleteNoteJob.perform_later(params[:id])

    respond_to do |format|
      format.html do
         redirect_to notes_url
         flash[:success] = 'Sua nota será deletada em breve!' 
      end
      format.json { head :no_content }
    end
  end

  private
  
  # Note params

  def note_params
    params.require(:note).permit(:title, :description)
  end

  # Sets

  def set_note
    begin
      @note = Note.find(params[:id])
    rescue => err
      invalidate_note
    end
  end

  def set_note_owner(note)
    note.user_id = current_user.id
  end

  def set_users_notes
    @notes = Note.all.where(user_id: current_user)
  end

  # Routes

  def validate_user_note
    unless @note.user_id == current_user.id
      invalidate_note
    end
  end

  def invalidate_note
    flash[:danger] = "Nota #{params[:id]} não encontrada."
    redirect_to notes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/notes.html.erb
<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>NotesApp - Layout Notes</title>
        
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        
        <%= stylesheet_link_tag  'application' %>
        <%= stylesheet_link_tag  'notes' %>
    </head>
      
      <body id="page-top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
          <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none"></span>
            <span class="d-none d-lg-block">
              <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="" alt="">
            </span>
          </a>
          <h6> Bem vindo, <%= current_user.email %> </h6> <br />
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Minhas notas', notes_path, class:"nav-link js-scroll-trigger" %>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#experience">Configurações</a>
              </li>
              <li class="nav-item">
                <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "nav-link js-scroll-trigger"%>
              </li>
            </ul>
          </div>
        </nav>

        <div class="container-fluid p-0">
          <%= yield %>
        </div>
        <%= javascript_include_tag  'notes' %>
      </body>
</html>

app/views/notes/_form.html.erb
<div class="container">
<div class="row">
<div class="container-fluid px-sm-5">
  <section class="resume-section p-lg-5 d-flex align-items-center" id="note">
    <div class="w-100">
      <%= form_with(model: note, local: true) do |form| %>
        <% if note.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
            <ul>
            <% note.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <h4><%= form.label :title, "Título" %> </h4>
          <%= form.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group shadow-textarea">
          <h4> <%= form.label :description, "Descrição" %></h4>
          <%= form.text_area :description, class:"form-control z-depth-1", rows:"20" %>
        </div>
        <div class="form-group">
          <%= form.submit 'Salvar!', class:"btn btn-outline-success"%>
          <%= link_to "Voltar", notes_path, class:"btn btn-outline-dark"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<div class="container">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>
<div class="row">
<div class="container-fluid px-sm-5">
  <section class="resume-section p-lg-5 d-flex align-items-center" id="note">
    <div class="w-100">
      <div class="header-title"><h2 class="mb-5"> Minhas notas </h2></div>
      <% @notes.each do |note| %>
        <div class="resume-item d-flex flex-column flex-md-row justify-content-between p-3 p-lg-5 shadow p-3 mb-5 rounded" style="background-color: #FFD700;">
          <div class="resume-content">
            <h3 class="mb-0"><%= note.title %> </h3> <br />
            <div> <%= note.description %> </div>
          </div>
          <div class="resume-date text-md-right"><br /> 
            <span class="text-primary"> dd/mm/yyyy </span> <br />
            <span class="text-primary"><%= link_to 'Show', note %> <br />
          <span class="text-primary"><%= link_to 'Edit', edit_note_path(note) %></span><br />
            <span class="text-primary"><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></span><br />
          </div>
        </div>
        <hr class="m-0"> <br />
      <% end %>
    </div>
  </section>
  <section class="p-sm-5 d-flex align-items-center">
      <div class="new-note-btn btn btn-warning"> <%= link_to 'Nova Nota', new_note_path %> </div>
  </section>
</div>
</div>
</div>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div class="container">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>
<div class="row">
<div class="container-fluid px-sm-5">
  <section class="resume-section p-lg-5 d-flex align-items-center" id="note">
    <div class="w-100">
      <div class="header-title"><h2 class="mb-5"> NOTA <%= @note.id%> </h2></div>
        <div class="resume-item d-flex flex-column flex-md-row justify-content-between p-3 p-lg-5 shadow p-3 mb-5 rounded" style="background-color: #FFD700; height: 40em">
          <div class="resume-content">
            <h3 class="mb-0"><%= @note.title %> </h3> <br />
            <div> <%= @note.description %> </div>
          </div>
          <div class="resume-date text-md-right">
            <span class="text-primary"> dd/mm/yyyy </span> <br />
            <span class="text-primary"><%= link_to 'Show', @note %> <br />
          <span class="text-primary"><%= link_to 'Edit', edit_note_path(@note) %></span> <br />
            <span class="text-primary"><%= link_to 'Destroy', @note, method: :delete, data: { confirm: 'Are you sure?' } %></span> <br />
          </div>
        </div>
        <hr class="m-0"> <br />
    </div>
  </section>
  <section class="p-sm-5 d-flex align-items-center">
      <div class="new-note-btn btn btn-warning"> <%= link_to 'Voltar', notes_path %> </div>
  </section>
</div>
</div>
</div>